In [1]:
import pandas as pd
import numpy as np

In [2]:
matriz = pd.read_csv('Z:/01 base_datos/06 matriz_distancia_FMS/20260529_matriz distancias.csv', encoding='latin')

matriz

,ï»¿Tipo de Servicio,Id LÃ­nea,LÃ­nea,Configuraciones,ConfiguraciÃ³n Activa,Id SublÃ­nea,Id Ruta,Nombre Ruta,Sentido,Id Nodo,Etiqueta Nodo,Nombre Nodo,PosiciÃ³n,Coordenada X,Coordenada Y,Atributos
0,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52845.0,247A05_TM,247A05_Br. La Esperanza II,0.0,595348.0,521193.0,"SinÃ³ptico, Horario GOAL, Punto de control (TM..."
1,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52806.0,222A05_TM,222A05_Hospital de EngativÃ¡ EmaÃºs,138.0,595258.0,521149.0,NaN
2,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52365.0,068A05_TM,068A05_Liceo SalomÃ³n Sabio,425.0,595014.0,520997.0,NaN
3,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52442.0,110A05_TM,110A05_Br. Sabana del Dorado,686.0,594933.0,520819.0,NaN
4,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52369.0,070A05_TM,070A05_Br. Sabana del Dorado,964.0,595091.0,520593.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14710,URBANO,10691,DA218,2,2,2490.0,12750.0,DA218_CiclovÃ¬a_V2,Circular,52364.0,067A05_TM,067A05_Terminal TUYO,40543.0,595410.0,520746.0,NaN
14711,URBANO,10691,DA218,2,2,2490.0,12750.0,DA218_CiclovÃ¬a_V2,Circular,52368.0,069B05_TM,069B05_C.C. Muisca,40799.0,595280.0,520965.0,NaN
14712,URBANO,10691,DA218,2,2,2490.0,12750.0,DA218_CiclovÃ¬a_V2,Circular,52371.0,071A05_TM,071A05_Pq. EngativÃ¡,41090.0,595147.0,521222.0,NaN
14713,URBANO,10691,DA218,2,2,2490.0,12750.0,DA218_CiclovÃ¬a_V2,Circular,52373.0,073A05_TM,073A05_Col. Tomas Alva Edison,41384.0,595031.0,521487.0,NaN
14714,URBANO,10691,DA218,2,2,2490.0,12750.0,DA218_CiclovÃ¬a_V2,Circular,52372.0,072A05_TM,072A05_Br. La Tortigua,41413.0,595019.0,521501.0,"SinÃ³ptico, Horario GOAL, Punto de control (TM..."

In [4]:
# function to find the value closest to the 25th percentile
def closest_to_25_percentile(group):
    q25 = np.percentile(group['PosiciÃ³n'], 25)
    closest_value = group.iloc[(group['PosiciÃ³n'] - q25).abs().argsort().iloc[0]]
    return closest_value

#Apply for group
result = matriz.groupby(['Id LÃ­nea', 'Id Ruta'], group_keys=False).apply(closest_to_25_percentile)

result

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_7028\3605872728.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = matriz.groupby(['Id LÃ­nea', 'Id Ruta'], group_keys=False).apply(closest_to_25_percentile)

                  ï»¿Tipo de Servicio  Id LÃ­nea LÃ­nea  Configuraciones  \
Id LÃ­nea Id Ruta
10184     10415.0              URBANO      10184    740                1
          12774.0              URBANO      10184    740                2
10194     10425.0              URBANO      10194    539                1
          10426.0              URBANO      10194    539                1
          12785.0              URBANO      10194    539                2
...                               ...        ...    ...              ...
10690     12722.0              URBANO      10690  DL219                2
10691     12398.0              URBANO      10691  DA218                1
          12399.0              URBANO      10691  DA218                1
          12746.0              URBANO      10691  DA218                2
          12750.0              URBANO      10691  DA218                2

                   ConfiguraciÃ³n Activa  Id SublÃ­nea  Id Ruta  \
Id LÃ­nea Id Ruta
10184     10415.0                      2         338.0  10415.0
          12774.0                      2        2521.0  12774.0
10194     10425.0                      2         342.0  10425.0
          10426.0                      2         342.0  10426.0
          12785.0                      2        2530.0  12785.0
...                                  ...           ...      ...
10690     12722.0                      2        2463.0  12722.0
10691     12398.0                      2        2127.0  12398.0
          12399.0                      2        2128.0  12399.0
          12746.0                      2        2489.0  12746.0
          12750.0                      2        2490.0  12750.0

                             Nombre Ruta   Sentido  Id Nodo Etiqueta Nodo  \
Id LÃ­nea Id Ruta
10184     10415.0                 740_V1  Circular  51293.0     098C09_TM
          12774.0                 740_V2  Circular  51293.0     098C09_TM
10194     10425.0             539_Ida_V1       Ida  53262.0     019A12_TM
          10426.0          539_Vuelta_V1    Vuelta  51400.0     130A04_TM
          12785.0             539_Ida_V2       Ida  53262.0     019A12_TM
...                                  ...       ...      ...           ...
10690     12722.0  DL219_V2_CiclovÃ­a_V2  Circular  52865.0     002D06_TM
10691     12398.0               DA218_V1  Circular  56831.0     006A00_TM
          12399.0     DA218_CiclovÃ­a_V1  Circular  51215.0     074A04_TM
          12746.0               DA218_V2  Circular  51215.0     074A04_TM
          12750.0     DA218_CiclovÃ¬a_V2  Circular  56831.0     006A00_TM

                                           Nombre Nodo  PosiciÃ³n  \
Id LÃ­nea Id Ruta
10184     10415.0                      098C09_Floralia    17715.0
          12774.0                      098C09_Floralia    17383.0
10194     10425.0                 019A12_Br. La Aurora     8949.0
          10426.0                     130A04_Uniminuto     9516.0
          12785.0                 019A12_Br. La Aurora     8949.0
...                                                ...        ...
10690     12722.0          002D06_Br. Granjas de Techo    14876.0
10691     12398.0  006A00_Monumento Rafael Uribe Uribe    12206.0
          12399.0              074A04_Br. San Fernando    11632.0
          12746.0              074A04_Br. San Fernando    11290.0
          12750.0  006A00_Monumento Rafael Uribe Uribe    11864.0

                   Coordenada X  Coordenada Y  \
Id LÃ­nea Id Ruta
10184     10415.0      596219.0      509753.0
          12774.0      596219.0      509753.0
10194     10425.0      597293.0      499810.0
          10426.0      600214.0      520851.0
          12785.0      597293.0      499810.0
...                         ...           ...
10690     12722.0      598286.0      513139.0
10691     12398.0      602948.0      515855.0
          12399.0      602494.0      516206.0
          12746.0      602494.0      516206.0
          12750.0      602948.0      515855.0

                                                Atributos
Id LÃ­nea Id Ruta
10184     10415.0  SinÃ³ptico, Punto de control (TM-GOAL)
          12774.0  SinÃ³ptico, Punto de control (TM-GOAL)
10194     10425.0                                     NaN
          10426.0                                     NaN
          12785.0                                     NaN
...                                                   ...
10690     12722.0                                     NaN
10691     12398.0                                     NaN
          12399.0                                     NaN
          12746.0                                     NaN
          12750.0                                     NaN

[129 rows x 16 columns]

In [5]:
#Export data
result.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2025/vacio_25%.csv', sep=';', index=False)